# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.1.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip

  approval-deploy:
    docker:
        - image: cimg/python:3.12

    steps:
      - run:
          name: Install SSH Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client
      - add_ssh_keys:
          fingerprints:
            - SSHA256:rv9Idq7QWNCXoSUZFHyQ1B0fcqmR7NOT9xwtELwlxF8
      - run:
          name: Deploy to Server
          command: |
            ssh ecs-user@121.43.134.161 'cd softwares/ && git pull origin main && git clone https://github.com/django/django.git && pip install -e django/ && pip install -r requirements.txt && python manage.py runserver collectstatic --noinput'


workflows:
  do-it-all:
    jobs:
      - build-and-test

      - approval-deploy:
          type: approval
          name: deploy
          requires:
            - build-and-test